# Start local Supabase (if CLI installed) and run the app via Docker Compose.
$ErrorActionPreference = "Stop"
$Root = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
Set-Location $Root

if (-not (Test-Path ".env.docker")) {
  Copy-Item ".env.docker.example" ".env.docker"
  Write-Host "Created .env.docker from .env.docker.example"
}

$supabase = Get-Command supabase -ErrorAction SilentlyContinue
if ($supabase) {
  Write-Host "Starting local Supabase via Supabase CLI…"
  supabase start
  Write-Host "Applying migrations…"
  supabase db reset --local

  $generated = @{}
  supabase status -o env 2>$null | ForEach-Object {
    if ($_ -match '^([^=]+)=(.*)$') { $generated[$Matches[1]] = $Matches[2] }
  }
  if ($generated.API_URL) {
    @"
# Auto-generated by docker/up.ps1
VITE_SUPABASE_URL=$($generated.API_URL)
VITE_SUPABASE_PUBLISHABLE_KEY=$($generated.ANON_KEY)
SUPABASE_URL=http://host.docker.internal:54321
SUPABASE_PUBLISHABLE_KEY=$($generated.ANON_KEY)
SUPABASE_SERVICE_ROLE_KEY=$($generated.SERVICE_ROLE_KEY)
ADMIN_BOOTSTRAP_EMAILS=operator@example.com
"@ | Set-Content -Path ".env.docker" -Encoding utf8
    Write-Host "Updated .env.docker with local Supabase keys"
  }
} else {
  Write-Host "Supabase CLI not found — skipping supabase start."
  Write-Host "Install: https://supabase.com/docs/guides/cli/getting-started"
}

docker compose up --build @args
