#!/usr/bin/env sh
set -eu

ROOT="$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)"
cd "$ROOT"

if [ ! -f .env.docker ]; then
  cp .env.docker.example .env.docker
  echo "Created .env.docker from .env.docker.example"
fi

if command -v supabase >/dev/null 2>&1; then
  echo "Starting local Supabase (Docker) via Supabase CLI…"
  supabase start

  echo "Applying migrations to local database…"
  supabase db reset --local

  if supabase status -o env > .env.docker.generated 2>/dev/null; then
    echo "Wrote .env.docker.generated from 'supabase status -o env'"
    # Map CLI env names to app env names when present
    if grep -q '^API_URL=' .env.docker.generated 2>/dev/null; then
      API_URL="$(grep '^API_URL=' .env.docker.generated | cut -d= -f2-)"
      ANON_KEY="$(grep '^ANON_KEY=' .env.docker.generated | cut -d= -f2-)"
      SERVICE_KEY="$(grep '^SERVICE_ROLE_KEY=' .env.docker.generated | cut -d= -f2-)"
      cat > .env.docker <<EOF
# Auto-generated by docker/up.sh — edit as needed
VITE_SUPABASE_URL=${API_URL}
VITE_SUPABASE_PUBLISHABLE_KEY=${ANON_KEY}
SUPABASE_URL=http://host.docker.internal:54321
SUPABASE_PUBLISHABLE_KEY=${ANON_KEY}
SUPABASE_SERVICE_ROLE_KEY=${SERVICE_KEY}
ADMIN_BOOTSTRAP_EMAILS=${ADMIN_BOOTSTRAP_EMAILS:-operator@example.com}
EOF
      echo "Updated .env.docker with local Supabase keys"
    fi
  fi
else
  echo "Supabase CLI not found — skipping 'supabase start'."
  echo "Install: https://supabase.com/docs/guides/cli/getting-started"
  echo "Or point .env.docker at a cloud Supabase project."
fi

exec docker compose up --build "$@"
